#!/bin/bash
cd "$(dirname "$0")"  # jump to curdir

# Pass these on the command line.
oscodename=${1:-debian/bullseye}  # debian/bullseye
upname=sipp
upversion=${2:-3.6.1}       # sipp version
debversion=${3:-0osso1}     # deb build version, e.g. 0osso1

echo "Usage: $0 [debian/bullseye [3.6.1 [0osso1]]]"
echo ".. continuing"

osdistro=${oscodename%/*}   # debian (or ubuntu)
oscodename=${oscodename#*/} # bullseye (or bionic)
osdistshort=${osdistro:0:3} # deb (or ubu)
case $osdistro/$oscodename in
debian/forky)   oscodenum=14;;
debian/trixy)   oscodenum=13;;
debian/bookworm)oscodenum=12;;
debian/bullseye)oscodenum=11;;
ubuntu/noble)   oscodenum=24.04;;
ubuntu/jammy)   oscodenum=22.04;;
ubuntu/focal)   oscodenum=20.04;;
*) oscodenum=0
esac
_shortver=$osdistshort$oscodenum

# Update changelog
sed -i -e "1s/+\\(deb\\|ubu\\)[0-9.]*) [a-z]\\+;/+$_shortver) $oscodename;/" \
    changelog

# Docker disallows certain tokens in versions.
dockversion=$(echo build-${upname}-${upversion}-${debversion}-${oscodename} |
    sed -e 's/[^0-9A-Za-z_.-]/_/g')

# Will build files.
if ! docker build \
    --pull \
    --ulimit nofile=512 \
    --build-arg osdistro=$osdistro \
    --build-arg osdistshort=$osdistshort \
    --build-arg oscodename=$oscodename \
    --build-arg upname=$upname \
    --build-arg upversion=$upversion \
    --build-arg debversion=$debversion \
    -t $dockversion \
    -f Dockerfile \
    .
then
    echo "fail" >&2
    exit 1
fi

# Copy files to ./Dockerfile.out
test -d Dockerfile.out/$oscodename || mkdir -p Dockerfile.out/$oscodename
docker run $dockversion sh -c 'cd /dist; tar -zc *' |
    tar -zxvC Dockerfile.out/$oscodename/ |
    sed -e 's#$# -> Dockerfile.out/'$oscodename'/#'
